//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceMerge.DemoWebApp {
    
    
    public partial class WebForm1 {
        
        /// <summary>
        /// RawResource11 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource11;
        
        /// <summary>
        /// RawResource1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource1;
        
        /// <summary>
        /// RawResource2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource2;
        
        /// <summary>
        /// RawResource3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource3;
        
        /// <summary>
        /// RawResource4 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource4;
        
        /// <summary>
        /// RawResource5 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource5;
        
        /// <summary>
        /// RawResource6 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource6;
        
        /// <summary>
        /// RawResource7 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource7;
        
        /// <summary>
        /// RawResource8 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource8;
        
        /// <summary>
        /// RawResource9 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource9;
        
        /// <summary>
        /// WebUserControl11 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.DemoWebApp.WebUserControl1 WebUserControl11;
        
        /// <summary>
        /// RawResource12 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource12;
        
        /// <summary>
        /// RawResource10 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ResourceMerge.Core.RawResource RawResource10;
    }
}
